#!/usr/bin/perl

use Scalar::Util 'looks_like_number';

use CGI;
$q = new CGI;
my $_0 = $q->param('_0');
my $_1 = $q->param('_1');
my $_2 = $q->param('_2');
my $_3 = $q->param('_3');
my $_4 = $q->param('_4');
my $_5 = $q->param('_5');
my $_6 = $q->param('_6');
my $p = $q->param('p');
my $s = $q->param('s');

print "Content-type: text/html\n\n";

my $move = "AI moves to: e\ninvalid URL";

if(looks_like_number($_0) && looks_like_number($_1) && looks_like_number($_2) && looks_like_number($_3) && looks_like_number($_4) && looks_like_number($_5) && looks_like_number($_6) && looks_like_number($p) && looks_like_number($s)){
	$move = `./runAI $_0 $_1 $_2 $_3 $_4 $_5 $_6 $p $s`;
}

print "$move\n";

if($s == 1){
	my $datestring = localtime();
	my $filename = './log.txt';
	open(my $fh, ">>", $filename) or print "Could not open file '$filename' $!";
	print $fh "\n\n\n____________________________$datestring:____________________________\n";
	print $fh "/cgi-bin/move?_0=$_0&_1=$_1&_2=$_2&_3=$_3&_4=$_4&_5=$_5&_6=$_6&p=$p&s=$s\n";
	print $fh "$move\n";
	close $fh;
}

EOF
